/**
 * THIRD_PARTY_NOTICES.md, generated from what the bundle actually inlines.
 *
 *   npx tsx scripts/third-party-notices.ts --write   # regenerate (run by `npm run build`)
 *   npx tsx scripts/third-party-notices.ts           # exit 1 if the committed file is stale
 *
 * `dist/mcp-server.mjs` inlines its dependencies, so it is a copy of "substantial portions" of each
 * one and must carry their licence notices. package.json naming a dependency does not put its notice
 * into a standalone bundle. The package set is read from esbuild's own per-module path comments in
 * the bundle, not from package.json, so a dependency that is declared but tree-shaken away is not
 * listed and a transitive one that is inlined is. Each entry is the full licence file of the exact
 * installed version.
 *
 * Tempora's Apache-2.0 licence covers Tempora's code only. These components keep their own licences.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const pkgDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const BUNDLE = resolve(pkgDir, "dist/mcp-server.mjs");
const NOTICES = resolve(pkgDir, "THIRD_PARTY_NOTICES.md");

export interface BundledPackage {
  name: string;
  version: string;
  license: string;
  licenceText: string;
}

/** Package directories (relative to the package root, as esbuild wrote them) that the bundle inlines. */
export function bundledPackageDirs(bundle: string): string[] {
  const dirs = new Set<string>();
  for (const m of bundle.matchAll(/^\/\/ (\S*node_modules\/(?:@[^/\s]+\/)?[^/\s]+)\//gm)) if (m[1]) dirs.add(m[1]);
  return [...dirs].sort();
}

export function readPackage(dir: string): BundledPackage {
  const abs = resolve(pkgDir, dir);
  const pj = JSON.parse(readFileSync(resolve(abs, "package.json"), "utf8")) as { name: string; version: string; license?: string };
  const file = readdirSync(abs).find((f) => /^(licen[cs]e|copying)(\.(md|txt))?$/i.test(f));
  if (!file) throw new Error(`${pj.name}@${pj.version} is inlined in the bundle but ships no licence file`);
  return { name: pj.name, version: pj.version, license: pj.license ?? "UNKNOWN", licenceText: readFileSync(resolve(abs, file), "utf8").trim() };
}

export function renderNotices(pkgs: BundledPackage[]): string {
  const sorted = [...pkgs].sort((a, b) => a.name.localeCompare(b.name));
  const head = `# Third-party notices

\`dist/mcp-server.mjs\` is a single file that includes the third-party components below. Each
component remains under its own licence, reproduced here in full for the exact version included.
Tempora Labs' Apache License 2.0 (\`LICENSE\`) applies to Tempora's own code, not to these
components.

This file is generated by \`scripts/third-party-notices.ts\` from the bundle itself. Do not edit it
by hand.

| Component | Version | Licence |
|---|---|---|
${sorted.map((p) => `| \`${p.name}\` | ${p.version} | ${p.license} |`).join("\n")}
`;
  const bodies = sorted.map((p) => `\n## ${p.name} ${p.version} (${p.license})\n\n\`\`\`text\n${p.licenceText}\n\`\`\`\n`);
  return head + bodies.join("");
}

export function expectedNotices(): string {
  return renderNotices(bundledPackageDirs(readFileSync(BUNDLE, "utf8")).map(readPackage));
}

function main(): void {
  const want = expectedNotices();
  if (process.argv.includes("--write")) {
    writeFileSync(NOTICES, want);
    console.log("✓ THIRD_PARTY_NOTICES.md written");
    return;
  }
  let have = "";
  try {
    have = readFileSync(NOTICES, "utf8");
  } catch {
    /* missing is stale */
  }
  if (have !== want) {
    console.log("✗ THIRD_PARTY_NOTICES.md is stale: run npx tsx scripts/third-party-notices.ts --write");
    process.exit(1);
  }
  console.log("✓ THIRD_PARTY_NOTICES.md matches the bundle");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
