/**
 * Builds the connect page into ../dist/connect-page.js (one minified file, no source map).
 *
 * 🔴 WalletConnect / Reown code is STUBBED OUT, not merely disabled. Privy's React SDK reaches it
 * through a dynamic import that runs only for a WalletConnect login, which this page never offers
 * (`externalWallets.walletConnect.enabled: false`, and only detected browser wallets are listed).
 * Without the stub, a bundle still inlines ~29 `@walletconnect/*` / `@reown/*` packages, 13 of them
 * under the WalletConnect / Reown Community License — not an open-source licence — which this
 * Apache-2.0 repository does not ship. Measured 2026-10-03: with the stub the bundle carries zero of
 * them (5.3 MB → 3.6 MB) and the Privy window still opens and lists email, Google, Apple, X and
 * wallets. The build fails if any of those packages comes back in.
 */
import { build } from "esbuild";

const stub = {
  name: "no-walletconnect",
  setup(b) {
    b.onResolve({ filter: /^@(walletconnect|reown)\// }, (a) => ({ path: a.path, namespace: "no-walletconnect" }));
    b.onLoad({ filter: /.*/, namespace: "no-walletconnect" }, () => ({
      contents:
        'module.exports = new Proxy({}, { get(_, k) { if (k === "__esModule") return true; if (k === "then") return undefined; throw new Error("WalletConnect is not included in this page"); } });',
      loader: "js",
    }));
  },
};

const result = await build({
  entryPoints: ["src/main.tsx"],
  bundle: true,
  minify: true,
  format: "iife",
  platform: "browser",
  target: ["es2020"],
  define: { "process.env.NODE_ENV": '"production"' },
  loader: { ".woff2": "dataurl" },
  legalComments: "none",
  outfile: "../dist/connect-page.js",
  metafile: true,
  plugins: [stub],
  logLevel: "warning",
});

const leaked = Object.keys(result.metafile.inputs).filter((p) => /node_modules\/@(walletconnect|reown)\//.test(p));
if (leaked.length) {
  console.error(`WalletConnect/Reown code reached the bundle: ${leaked.slice(0, 5).join(", ")}${leaked.length > 5 ? " …" : ""}`);
  process.exit(1);
}
// Notices for exactly what the bundle inlines, each package's own licence file in full, written
// beside the root notices so it travels with the bundle (npm `files: dist` + the root file list,
// and the plugin copy).
const fs = await import("node:fs");
const path = await import("node:path");
const dirs = new Set();
for (const p of Object.keys(result.metafile.inputs)) {
  const m = p.match(/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//);
  if (m) dirs.add(m[1]);
}
const pkgs = [...dirs].map((d) => {
  const pj = JSON.parse(fs.readFileSync(path.join(d, "package.json"), "utf8"));
  const file = fs.readdirSync(d).find((f) => /^(licen[cs]e|copying)(\.(md|txt))?$/i.test(f));
  if (!file) {
    // A package that declares Apache-2.0 but ships no licence file (the @solana-program/* packages
    // Privy's SDK inlines do this) gets the canonical Apache-2.0 text, said plainly. Anything else
    // without a licence file stops the build: a notice cannot be invented.
    if (pj.license !== "Apache-2.0") throw new Error(`${pj.name}@${pj.version} is inlined in the page but ships no licence file`);
    const canonical = fs.readFileSync("../LICENSE", "utf8").trim();
    return { name: pj.name, version: pj.version, license: pj.license, text: `This package ships no licence file; its package.json declares Apache-2.0. The canonical text of that licence follows.\n\n${canonical}` };
  }
  return { name: pj.name, version: pj.version, license: pj.license ?? "see licence text", text: fs.readFileSync(path.join(d, file), "utf8").trim() };
});
const seen = new Map();
for (const p of pkgs) seen.set(`${p.name}@${p.version}`, p);
const sorted = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
const out = `# Third-party notices — the connect page

\`dist/connect-page.js\` is a single file that includes the third-party components below. Each
component remains under its own licence, reproduced here in full for the exact version included.
Tempora Labs' Apache License 2.0 (\`LICENSE\`) applies to Tempora Labs' own code, not to these components.
No WalletConnect or Reown component is included (see \`connect-page/build.mjs\`).

This file is generated by \`connect-page/build.mjs\` from the bundle itself. Do not edit it by hand.

| Component | Version | Licence |
|---|---|---|
${sorted.map((p) => `| \`${p.name}\` | ${p.version} | ${p.license} |`).join("\n")}
` + sorted.map((p) => `\n## ${p.name} ${p.version} (${p.license})\n\n\`\`\`text\n${p.text}\n\`\`\`\n`).join("");
fs.writeFileSync("../THIRD_PARTY_NOTICES.connect-page.md", out);
console.log(`dist/connect-page.js built; ${sorted.length} components in THIRD_PARTY_NOTICES.connect-page.md`);
